"Days active" = "Days active"
"Days since acceptation" = "Days since acceptation"
Status = "Status"
"Days left until reviews should be done" = "Days left until reviews should be done"
Initiator = "Initiator"
"Initiator review score" = "Initiator review score"
"Initiator App" = "Initiator App"
"Initiator app is payed" = "Initiator app is payed"
No = "No"
Delete = "Delete"
